name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      ASDF_CONCURRENCY: "3"
    steps:
      - name: Install depencies
        run: |
          brew install autoconf re2c bison pkg-config libiconv gd gmp libsodium libpq readline gettext bzip2 curl libffi libxml2 libxslt zlib icu4c oniguruma libzip

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: php --version
